name: change_maps_key
description: Change Google Maps API key 
version: 1.0.1
homepage: https://github.com/L-Salazar/change_maps_key
issue_tracker: https://github.com/L-Salazar/change_maps_key/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  change_maps_key: change_maps_key
